### ISSUE TITLE
Google + counter

### ISSUE THREAD

**Issue by Frostbourn** [meddelare/meddelare-node-server#3]
Google + always return "-1" value.

**Comment by joelpurra** [comment]
@Frostbourn: you're right. Thought it was a temporary issue, but perhaps not. Let's hope it's not as "bad" as #2.

Thanks for reporting this! No time estimate for completion yet. Patches are always welcome =)

**Comment by joelpurra** [comment]
@Frostbourn: actually, this was easy to fix -- it was just a regexp that was outdated. Fixed in meddelare/meddelare-node-counters#6.

Released as meddelare-counters v1.0.2 on NPM. The new version should be used automatically next time you upgrade/install/reinstall medddelare-node-server.
https://www.npmjs.com/package/meddelare-counters

Thanks for reporting the issue!
